package algonquin.cst2335.androidfinalproject.music;

import androidx.room.Database;
import androidx.room.RoomDatabase;

/**
 * Abstract database class for the music database.
 * This class defines the database for the music application which includes the Music entity.
 * It uses Room Database to provide an abstraction layer over SQLite.
 *
 * @version 3 The version number of the database. Update this number if the schema changes.
 */
@Database(entities = {Music.class}, version = 3)
public abstract class MusicDatabase extends RoomDatabase {

    /**
     * Abstract method to get the Music Data Access Object (DAO).
     * The implementation is automatically generated by Room.
     *
     * @return An instance of MusicDAO for accessing the music database.
     */
    public abstract MusicDAO musicDAO();
}
